src/java/model/clique/Node.java
package model.clique;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import model.review.ReviewDTO;

/**
 * This class represents Model object for Node providing
 * providername,reputation, regionLists,revRegionList,DirectList and
 * revDirectList.
 *
 * @author Hien
 */
public class Node {

    String providerName;
    int reputation = -1;
    boolean reputationChanged = false;
    List<Node> reachableNodes = new ArrayList<>();
    List<Path> regionList = new ArrayList<>();
    List<Path> revRegionList = new ArrayList<>();
    List<NodeDirectRelation> directList = new ArrayList<>();
    List<Node> revDirectList = new ArrayList<>();
    double density = 0;
    boolean isOneDirectNode = false;

    public boolean isIsOneDirectNode() {
        return isOneDirectNode;
    }

    public void setIsOneDirectNode(boolean isOneDirectNode) {
        this.isOneDirectNode = isOneDirectNode;
    }

    public String getProviderName() {
        return providerName;
    }

    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }

    public int getReputation() {
        return reputation;
    }

    public void setReputation(int reputation) {
        if ((this.reputation > -1) && (this.reputation != reputation)) {
            reputationChanged = true;
        }

        this.reputation = reputation;
    }

    public boolean isReputationChanged() {
        return reputationChanged;
    }

    public List<Node> getReachableNodes() {
        return reachableNodes;
    }

    public List<Path> getRegionList() {
        return regionList;
    }

    public void setRegionList(List<Path> regionList) {
        this.regionList = regionList;
    }

    public List<Path> getRevRegionList() {
        return revRegionList;
    }

    public void setRevRegionList(List<Path> revRegionList) {
        this.revRegionList = revRegionList;
    }

    public List<NodeDirectRelation> getDirectList() {
        return directList;
    }

    public void setDirectList(List<NodeDirectRelation> directList) {
        this.directList = directList;
    }

    public List<Node> getRevDirectList() {
        return revDirectList;
    }

    public void setRevDirectList(List<Node> revDirectList) {
        this.revDirectList = revDirectList;
    }

    public double getDensity() {
        return density;
    }

    public void setDensity(double density) {
        this.density = density;
    }

    public List<ReviewDTO> getAllReviews() {
        List<ReviewDTO> reviews = new ArrayList<>();
        for (NodeDirectRelation direct : directList) {
            reviews.addAll(direct.getReviews());
        }
        return reviews;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 23 * hash + Objects.hashCode(this.providerName);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Node other = (Node) obj;
        return Objects.equals(this.providerName, other.providerName);
    }

    @Override
    public String toString() {
        return "Node{" + "providerName=" + providerName + ", reputation=" + reputation + ", directList=" + directList + ", revDirectList=" + revDirectList + '}';
    }
}

src/java/clique/controllers/CliqueFilterController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clique.controllers;

import Exception.FilloException;
import Fillo.Connection;
import Fillo.Fillo;
import Fillo.Recordset;
import Utils.FilenameUtils;
import clique.database.ExcelDatabase;
import filters.CliqueFilter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.Serializable;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.inject.Named;
import javax.naming.NamingException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.Part;
import model.clique.Clique;
import model.clique.CliqueDAO;
import model.provider.ProviderDAO;
import model.provider.ProviderDTO;
import org.apache.commons.io.IOUtils;
import org.apache.myfaces.custom.fileupload.UploadedFile;

/**
 * This class manages all the actions related to Clique algorithm as well as the
 * load_validation_page results.
 *
 * @author hien_quan
 */
@Named
@SessionScoped
public class CliqueFilterController implements Serializable {

    CliqueFilter cliqueFilter = null;
    List<Clique> cliques = null;
    List<Clique> inputCliques = null;
    List<ProviderDTO> providers;
    int correctPercentage = -1;
    int truePosNum = 0;
    int trueNegNum = 0;
    int falsePosNum = 0;
    int falseNegNum = 0;
    double h;
    double threshold;
    boolean filterDone = false;
    boolean reloadDB = false;
    private DataModel<Clique> cliqueModel;
    private UploadedFile dbFile;
    private UploadedFile cliqueUpFile;
    private String dbFileName;
    private String cliqueFileName;
    private int currentStage = 0;

    Logger logger = Logger.getLogger(CliqueFilterController.class.getName());

    public int getCurrentStage() {
        return currentStage;
    }

    public void setCurrentStage(int currentStage) {
        this.currentStage = currentStage;
    }

    public List<ProviderDTO> getProviders() {
        return providers;
    }

    public void setProviders(List<ProviderDTO> providers) {
        this.providers = providers;
    }

    public UploadedFile getDbFile() {
        return dbFile;
    }

    public void setDbFile(UploadedFile dbFile) {
        this.dbFile = dbFile;
    }

    public UploadedFile getCliqueUpFile() {
        return cliqueUpFile;
    }

    public void setCliqueUpFile(UploadedFile cliqueUpFile) {
        this.cliqueUpFile = cliqueUpFile;
    }

    private String uploadFile(UploadedFile upFile) {
        String folderPath = "C:\\Clique";
        String fileName = null;
        System.out.println("File type: " + upFile.getContentType());
        System.out.println("File name: " + upFile.getName());
        System.out.println("File size: " + upFile.getSize() + " bytes");

        // Prepare filename prefix and suffix for an unique filename in upload folder.
        String prefix = FilenameUtils.getBaseName(upFile.getName());
        String suffix = FilenameUtils.getExtension(upFile.getName());

        // Prepare file and outputstream.
        File file = null;
        OutputStream output = null;

        try {
            // Create file with unique name in upload folder and write to it.
            file = File.createTempFile(prefix + "_", "." + suffix, new File(folderPath));
            output = new FileOutputStream(file);
            IOUtils.copy(upFile.getInputStream(), output);
            fileName = folderPath + "\\" + file.getName();

            // Show succes message.
            FacesContext.getCurrentInstance().addMessage("clique_filter", new FacesMessage(
                    FacesMessage.SEVERITY_INFO, "File upload succeed!", null));
        } catch (IOException e) {
            // Cleanup.
            if (file != null) {
                file.delete();
            }

            // Show error message.
            FacesContext.getCurrentInstance().addMessage("clique_filter", new FacesMessage(
                    FacesMessage.SEVERITY_ERROR, "File upload failed with I/O error.", null));

            // Always log stacktraces (with a real logger).
            e.printStackTrace();
        } finally {
            IOUtils.closeQuietly(output);
        }
        return fileName;
    }

    /**
     * This method load database
     *
     * @return null
     */
    public String loadDB() {
        try {
            dbFileName = uploadFile(dbFile);
            ExcelDatabase.setXlsPath(dbFileName);
            ExcelDatabase.storeData();

            ProviderDAO providerDAO = new ProviderDAO();
            providers = new ArrayList<>();
            providers.addAll(providerDAO.loadAll());

        } catch (Exception ex) {
            logger.log(Level.SEVERE, ex.getMessage() + " - " + ex.getCause());
        }
        return null;
    }

    public DataModel getCliqueModel() {
        return cliqueModel;
    }

    public boolean isReloadDB() {
        return reloadDB;
    }

    public void setReloadDB(boolean reloadDB) {
        this.reloadDB = reloadDB;
    }

    public boolean isFilterDone() {
        return filterDone;
    }

    public double getH() {
        return h;
    }

    public void setH(double h) {
        this.h = h;
    }

    public double getThreshold() {
        return threshold;
    }

    public void setThreshold(double threshold) {
        this.threshold = threshold;
    }

    public int getCorrectPercentage() {
        return correctPercentage;
    }

    public CliqueFilter getCliqueFilter() {
        return cliqueFilter;
    }

    public List<Clique> getCliques() {
        return cliques;
    }

    /**
     * This function loads the content of the validation stage 1 page.
     */
    public void load_validation_stage_1() {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();

        if (request.getParameter("correct") == null || request.getParameter("id") == null) {
            return;
        }

        int clique_providerString = Integer.valueOf(request.getParameter("id"));
        boolean correct = Boolean.valueOf(request.getParameter("correct"));
        for (Clique clique : cliques) {
            if (clique.getProvider_string().equals(clique_providerString)) {
                clique.setCorrect(correct);
                break;
            }
        }
    }

    /**
     * This Method load filter method in the CliqueFilter Model
     *
     * @return null
     * @throws InterruptedException
     * @throws ParseException
     */
    public String filter() throws InterruptedException, ParseException, NamingException, SQLException {
        ProviderDAO providerDAO = new ProviderDAO();
        if (providers == null || providers.isEmpty()) {
            providers = new ArrayList<>();
            providers.addAll(providerDAO.loadAll());
        }

        cliqueFilter = new CliqueFilter(h, threshold);
        cliques = cliqueFilter.filter();
        cliqueModel = new ListDataModel<>(cliques);
        filterDone = true;
        if (cliqueFileName == null || cliqueFileName.isEmpty()) {
            currentStage = 1;
        } else currentStage = 2;
        cliqueFileName = null;
        return null;
    }

    public String loadCliqueInputData() throws FilloException {
        cliqueFileName = uploadFile(cliqueUpFile);
        Fillo fillo = new Fillo();
        Connection connection = fillo.getConnection(cliqueFileName);
        Recordset recordset = connection.executeQuery("Select * from Clique");
        inputCliques = new ArrayList<>();
        while (recordset.next()) {
            Clique clique = new Clique();
            clique.setProvider_string(recordset.getField("provider_string"));
            clique.setCorrect(true);
            clique.setStrong(Boolean.getBoolean(recordset.getField("strong")));
            inputCliques.add(clique);
        }
        return null;
    }

    /**
     * This function loads content of validation stage 2.
     *
     * @throws ParseException
     */
    public void load_validation_stage_2() throws ParseException {
        resetPosNegNums();

        for (Clique clique : cliques) {
            if (inputCliques.contains(clique)) {
                clique.setCorrect(true);
                updateReputation(clique);
                truePosNum++;
            } else {
                falsePosNum++;
            }
        }
        falseNegNum = inputCliques.size() - truePosNum;
    }

    /**
     * This method reset all the positive and negative values.
     */
    private void resetPosNegNums() {
        truePosNum = 0;
        trueNegNum = 0;
        falseNegNum = 0;
        falsePosNum = 0;
    }

    /**
     * This method load the content of clique_detail page with stage number and
     * provider name
     *
     * @param clique
     * @param stage_num
     * @return
     */
    public String showCliqueDetail(Clique clique, int stage_num) {
        return "clique_detail.xhtml?stage_num=" + stage_num + "&clique=" + clique.getProvider_string() + "faces-redirect=true";
    }

    /**
     * This method do the verification
     */
    public void doneVerification() throws SQLException, NamingException {
        int correctNum = 0;
        CliqueDAO cliqueDAO = new CliqueDAO();
        for (Clique clique : cliques) {
            logger.info(clique.toString());
            if (clique.isCorrect()) {
                cliqueDAO.insert(clique);
                updateReputation(clique);
                correctNum++;
            }
        }

src/java/clique/controllers/SearchProviderController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clique.controllers;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.enterprise.context.*;
import javax.inject.Named;
import model.other.Criterion;

/**
 * This class manages search provider by criteria
 *
 * @author Kazim
 */
@Named
@SessionScoped
public class SearchProviderController implements Serializable {

    private List<Criterion> searchCriteria;

    public SearchProviderController() {
        searchCriteria = new ArrayList();
        searchCriteria.add(new Criterion());
    }

    public void setSearchCriteria(List<Criterion> searchCriteria) {
        this.searchCriteria = searchCriteria;
    }

    public List<Criterion> getSearchCriteria() {
        return searchCriteria;
    }

    /**
     * This function removes criteria from search criteria
     * @param criteria 
     */
    public void removeCriteria(Criterion criteria) {
        searchCriteria.remove(criteria);
    }
    /**
     * This function add search criteria to search criteria
     */
    public void addCriteria() {
        searchCriteria.add(new Criterion());
    }
}

web/clique_detail.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <f:metadata>
        <f:viewAction if="#{!(param.stage_num eq null)}" action="#{cliqueController.load(param.stage_num, param.clique, cliqueFilterController)}"/>
    </f:metadata>

    <ui:composition template="template.xhtml">
        <ui:define name="navbar">
            <h:link outcome="index" value="Home"/> &rarr; 
            <h:link outcome="clique_filter" value="Clique Filter"/> &rarr; 
            <h:panelGroup rendered="#{cliqueController.stageNum eq 1}">
                <h:link outcome="clique_validation_stage1" value="Validation Stage 1"/> &rarr; 
            </h:panelGroup>
            <h:panelGroup rendered="#{cliqueController.stageNum eq 2}">
                <h:link outcome="clique_validation_stage2" value="Validation Stage 2"/> &rarr; 
            </h:panelGroup>
            Clique Detail
        </ui:define>
        <ui:define name="subtitle">Clique Detail</ui:define>
        <ui:define name="page_content">
            <h:panelGroup rendered="#{cliqueController.stageNum == 2}">
                <h:outputText value="Correct clique? " style="padding-left: 5px; font-weight: bold"/>
                <h:graphicImage url="/resources/image/check-icon.png" rendered="#{cliqueController.clique.correct}"/>
                <h:graphicImage url="/resources/image/uncheck-icon.png" rendered="#{not cliqueController.clique.correct}"/>
            </h:panelGroup>
            <h:inputHidden value="#{cliqueController.clique.provider_string}"/>
            <h:inputHidden value="#{cliqueController.stageNum}"/>
            <h:dataTable value="#{cliqueController.clique.nodes}" var="node">
                <h:column>
                    <h:dataTable value="#{node.allReviews}" var="review" border="1" captionClass="caption" style="width: 100%"
                                 columnClasses="cliqueDetail-toCol,cliqueDetail-reviewCol,cliqueDetail-ratingCol,cliqueDetail-dateCol">
                        <f:facet name="caption">
                            <h:outputText class="tableCaption" value="From: #{node.providerName}"/>
                        </f:facet>
                        <h:column>
                            <f:facet name="header">To</f:facet>
                            <h:outputText value="#{cliqueController.getReviewedProvider(review)}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Review</f:facet>
                            <h:outputText value="#{cliqueController.getReview(review)}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Rating</f:facet>
                            <h:outputText value="#{cliqueController.getRatingStar(review)}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Date</f:facet>
                            <h:outputText value="#{cliqueController.getPublishDate(review)}"/>
                        </h:column>
                    </h:dataTable>
                </h:column>
            </h:dataTable>
            <h:panelGroup rendered="#{cliqueController.stageNum == 1}">
                <h:button class="button" value="Cancel" outcome="clique_validation_stage1"/>
                <h:commandButton class="button" value="Correct" 
                                 action="#{cliqueController.correct(true, cliqueFilterController)}"/>
                <h:commandButton class="button" value="Incorrect" 
                                 action="#{cliqueController.correct(false, cliqueFilterController)}"/>
            </h:panelGroup>
            <h:button rendered="#{cliqueController.stageNum == 2}" value="Back to Validation Page"
                      outcome="clique_validation_stage2" style="float: right"/>
        </ui:define>
    </ui:composition>
</html>

web/clique_filter.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:t="http://myfaces.apache.org/tomahawk">

    <ui:composition template="template.xhtml">
        <ui:define name="navbar">
            <h:link outcome="index" value="Home"/>
            &rarr; Clique Filter
        </ui:define>
        <ui:define name="subtitle">Filter Configuration</ui:define>
        <ui:define name="page_content">
            <table>
                <tr>
                    <td>
                        <label>Value of h: </label>
                    </td>
                    <td>
                        <h:inputText value="#{cliqueFilterController.h}"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label>Value of threshold: </label>
                    </td>
                    <td>
                        <h:inputText value="#{cliqueFilterController.threshold}"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label>Input file for clique: </label>
                    </td>
                    <td>
                        <t:inputFileUpload id="file1" value="#{cliqueFilterController.cliqueUpFile}"/>
                        <h:commandButton class="button" value="Load" 
                                         action="#{cliqueFilterController.loadCliqueInputData()}"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label>Input file for database: </label>
                    </td>
                    <td>
                        <t:inputFileUpload id="file2" value="#{cliqueFilterController.dbFile}"/>
                        <h:commandButton class="button" value="Load" 
                                         action="#{cliqueFilterController.loadDB()}"/>
                    </td>
                </tr>
                <tr>
                    <td align="right" colspan="2">
                        <h:button class="button" value="Show reputations" outcome="provider_reputation_list"/>
                        <h:commandButton class="button" value="Filter" action="#{cliqueFilterController.filter()}"/>
                    </td>
                </tr>
            </table>
            <h:panelGroup rendered="#{cliqueFilterController.filterDone}">
                <p>
                    <h:link value="Validation Stage 1" outcome="clique_validation_stage1.xhtml" rendered="#{cliqueFilterController.currentStage eq 1}"/>
                </p>
                <p>
                    <h:link value="Validation Stage 2" outcome="clique_validation_stage2.xhtml" rendered="#{cliqueFilterController.currentStage eq 2}"/>
                </p>
            </h:panelGroup>
        </ui:define>
    </ui:composition>
</html>

web/clique_validation_stage1.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <f:metadata>
        <f:viewAction action="#{cliqueFilterController.load_validation_stage_1()}"/>
    </f:metadata>
    <ui:composition template="template.xhtml">
        <ui:define name="navbar">
            <h:link outcome="index" value="Home"/> &rarr; 
            <h:link outcome="clique_filter" value="Clique Filter"/> &rarr; 
            Validation Stage 1
        </ui:define>
        <ui:define name="subtitle">Clique Filter - Validation Stage 1</ui:define>
        <ui:define name="page_content">
            <p>
                <span style="font-weight: bold">Execution time: </span>
                <h:outputText value="#{cliqueFilterController.cliqueFilter.executeTime} ms"/>
            </p>
            <p>
                <span style="font-weight: bold">Value of h: </span>
                <h:outputText value="#{cliqueFilterController.cliqueFilter.h}"/>
            </p>
            <p>
                <span style="font-weight: bold">Value of minimal density: </span>
                <h:outputText value="#{cliqueFilterController.cliqueFilter.threshold}"/>
            </p>

            <br/>
            <h2>List of Cliques</h2>
            <h:dataTable id="cliques" value="#{cliqueFilterController.cliqueModel}" var="clique">
                <h:column>
                    <div>
                        <h:outputText style="font-weight: bold" value="Clique #{cliqueFilterController.cliqueModel.rowIndex + 1}: "/>
                        <h:outputText value="#{clique.provider_string}"/>
                    </div>
                </h:column>
                <h:column>
                    <h:commandLink value="Show details" action="#{cliqueFilterController.showCliqueDetail(clique, 1)}"/>
                </h:column>
                <h:column>
                    <h:graphicImage url="/resources/image/check-icon.png" rendered="#{clique.correct}"/>
                    <h:graphicImage url="/resources/image/uncheck-icon.png" rendered="#{not clique.correct}"/>
                </h:column>
            </h:dataTable>
            <br/>
            <h:button value="Back to Clique Filter page" outcome="clique_filter.xhtml?faces-redirect=true"/>
            <h:commandButton value="Done Verification" action="#{cliqueFilterController.doneVerification()}" onclick="doneVerification()"/>
            <h:outputText value=" Accuracy: #{cliqueFilterController.correctPercentage}%" style="font-size: 20px; font-weight: bold; color: blue"
                          rendered="#{cliqueFilterController.correctPercentage >= 0}"/>
        </ui:define>
    </ui:composition>
</html>

web/clique_validation_stage2.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <f:metadata>
        <f:viewAction action="#{cliqueFilterController.load_validation_stage_2()}"/>
    </f:metadata>

    <ui:composition template="template.xhtml">
        <ui:define name="navbar">
            <h:link outcome="index" value="Home"/> &rarr; 
            <h:link outcome="clique_filter" value="Clique Filter"/> &rarr; 
            Validation Stage 2
        </ui:define>
        <ui:define name="subtitle">Clique Filter - Validation Stage 2</ui:define>
        <ui:define name="page_content">
            <p>
                <span style="font-weight: bold">Execution time: </span>
                <h:outputText value="#{cliqueFilterController.cliqueFilter.executeTime} ms"/>
            </p>
            <p>
                <span style="font-weight: bold">Value of h: </span>
                <h:outputText value="#{cliqueFilterController.cliqueFilter.h}"/>
            </p>
            <p>
                <span style="font-weight: bold">Value of minimal density: </span>
                <h:outputText value="#{cliqueFilterController.cliqueFilter.threshold}"/>
            </p>

            <br/>
            <h2>List of Cliques</h2>
            <h:dataTable id="cliques" value="#{cliqueFilterController.cliqueModel}" var="clique">
                <h:column>
                    <div>
                        <h:outputText style="font-weight: bold" value="Clique #{cliqueFilterController.cliqueModel.rowIndex + 1}: "/>
                        <h:outputText value="#{clique.provider_string}"/>
                    </div>
                </h:column>
                <h:column>
                    <h:commandLink value="Show details" action="#{cliqueFilterController.showCliqueDetail(clique, 2)}"/>
                </h:column>
                <h:column>
                    <h:graphicImage url="/resources/image/check-icon.png" rendered="#{clique.correct}"/>
                    <h:graphicImage url="/resources/image/uncheck-icon.png" rendered="#{not clique.correct}"/>
                </h:column>
            </h:dataTable>

            <br/>
            <h2>Validation Result</h2>
            <table id="validation_result" border="1">
                <tr>
                    <td></td>
                    <th>Positives</th>
                    <th>Negatives</th>
                </tr>
                <tr>
                    <th>True</th>
                    <td><h:outputText value="#{cliqueFilterController.truePosNum}"/></td>
                    <td><h:outputText value="#{cliqueFilterController.trueNegNum}"/></td>
                </tr>
                <tr>
                    <th>False</th>
                    <td><h:outputText value="#{cliqueFilterController.falsePosNum}"/></td>
                    <td><h:outputText value="#{cliqueFilterController.falseNegNum}"/></td>
                </tr>
                <p style="font-size: 20px; font-weight: bold; color: blue">
                    <h:outputText value="Precision: #{cliqueFilterController.precisionPercentage}%"/>
                    <br/>
                    <h:outputText value="Recall: #{cliqueFilterController.recallPercentage}%"/>
                </p>
            </table>
            <h:button value="Back to Clique Filter page" outcome="clique_filter.xhtml?faces-redirect=true"/>
        </ui:define>
    </ui:composition>
</html>

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <ui:composition template="template.xhtml">
        <ui:define name="navbar">
            Home
        </ui:define>
        <ui:define name="subtitle">Welcome to Review Filter</ui:define>
        <ui:define name="page_content">
            <ul>
                <li>
                    <h:link value="Ballot Stuffing Filter"/>
                </li>
                <li>
                    <h:link value="Bad mouthing Filter"/>
                </li>
                <li>
                    <h:link value="Spammer Group Filter"/>
                </li>
                <li>
                    <h:link value="Clique Filter" outcome="clique_filter"/>
                </li>
            </ul>
        </ui:define>
    </ui:composition>
</html>

web/searchProvider.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Reviewer Filter</title>
        <h:outputStylesheet name="general.css" library="css"/>
    </h:head>
    <h:body>
        <h1>Search Criteria</h1>
        <h:form>
            <h:dataTable id="tblFields" value="#{searchProviderController.searchCriteria}" var="criterion">
                <h:column>
                    <h:inputText value="#{criterion.value}" />
                </h:column>
                <h:column>
                    <h:commandButton value="Remove" action="#{searchProviderController.removeCriteria(criterion)}"/>
                </h:column>
            </h:dataTable>

            <h:commandButton class="button" value="Add" action="#{searchProviderController.addCriteria}"/>
            <h:commandButton class="button" value="Filter" action="clique_filter.xhtml?faces-redirect=true"/>
        </h:form>
    </h:body>
</html>
